### ISSUE TITLE
Nested transaction handling issues

### ISSUE THREAD

**Issue by martok** [popphp/pop-db#10]
The new nested transaction detection on `AdapterInterface` implementors doesn't count nesting right: in each `beginTransaction`, the counter should be incremented regardless of if a new transaction was started or not, or the commit/rollback level will not add up.

For example in `Adapter\Pgsql`, but all do the same:
```php
    public function beginTransaction(): Pgsql
    {
        if ($this->transactionDepth == 0) {
            $this->query('BEGIN TRANSACTION');
            $this->isTransaction = true;
        }
        $this->transactionDepth++;

        return $this;
    }
```

That still leaves a logic error that is hard to resolve: only the commit/rollback matching the main transaction does something. This is problematic if any nested "virtual" transaction already would have wanted a rollback previously (less so the other way around). You could end up with commited transactions that actually caused errors, something like this:
```
0 begin
1  begin
1    exception gets thrown, handler calls rollback but that gets skipped
0  commit --> partial/bad changes get committed
```
Unless you re-throw the exception and make sure every level has a try/catch/rollback, this can leave you with partial commits.

I've always found application-level transaction handling better in the long run, even if it requires some more planning. At least the DBMS will shout at you if anything is wrong...

**Comment by pitsolu** [comment]
@martok I believe differently RDBMs' handle transactions differently.

**Comment by martok** [comment]
For a reasonable solution, see [Doctrine DBAL](https://www.doctrine-project.org/projects/doctrine-dbal/en/3.7/reference/transactions.html).

If this is wanted, I'd volunteer to implement a similar logic.

**Comment by pitsolu** [comment]
If I'm getting you, it should check if you are currently in transaction mode `->inTransaction` within the `Record` then disable all `save()` functions if `true`?

**Comment by martok** [comment]
> If I'm getting you, it should check if you are currently in transaction mode `->inTransaction` within the `Record` then disable all `save()` functions if `true`?

What? Why would you do that? No, this issue has nothing to do with ActiveRecord at all (as indiciated by the fact that it is separate from the ActiveRecord issue). Nested transactions by themselves are complicated, and the current implementation is broken in two ways I detailed above.

**Comment by nicksagona** [comment]
Thanks for opening the issue @martok. I'll take a look at it when I can set aside some time this morning.

**Comment by pitsolu** [comment]
> > If I'm getting you, it should check if you are currently in transaction mode `->inTransaction` within the `Record` then disable all `save()` functions if `true`?
> 
> What? Why would you do that? No, this issue has nothing to do with ActiveRecord at all (as indiciated by the fact that it is separate from the ActiveRecord issue). Nested transactions by themselves are complicated, and the current implementation is broken in two ways I detailed above.

The idea is to persist all entities at the end in-case of erroneous code where someone missed a rollback.

**Comment by nicksagona** [comment]
Ok, I just pushed up a patch that should address the nested counting issue. Check out v6.3.0 and let me know if it's working as expected. Thanks.

**Comment by martok** [comment]
Closing as discussed in #8.
