### ISSUE TITLE
Re-org New Nested Txn Functionality 

### ISSUE THREAD

**Issue by nicksagona** [popphp/pop-db#13]
- Re-organize new nested transaction functionality for extensibility.

**Comment by nicksagona** [comment]
@martok - this is what I was thinking about re: the slight re-org. https://github.com/popphp/pop-db/tree/v6-dev-13/src/Adapter (for better OOP extensibility, etc)

**Comment by martok** [comment]
Yep, LGTM!

**Comment by nicksagona** [comment]
This is now live with v6.5.0
