### ISSUE TITLE
Error on modifying field of type datetime with current_timestamp

### ISSUE THREAD

**Issue by pitsolu** [popphp/pop-db#15]
Hi,

I am executing the statement below:

```php
$userSchema->defaultIs("CURRENT_TIMESTAMP");
```

and receiving the error message `SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created_at'`

```sql
ALTER TABLE `user` ADD `created_at` DATETIME DEFAULT 'CURRENT_TIMESTAMP';
```

I suppose the generated sql should be:

```sql
ALTER TABLE `user` ADD `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP;
```

**Comment by nicksagona** [comment]
Thanks for catching that. I just pushed patch up in the latest release (6.5.11) to fix that. Pull that down and let me know if it's working for you now.

**Comment by pitsolu** [comment]
@nicksagona It works great. Thanks! You still doing a great job. Keep it up.

Awesome framework!
