### ISSUE TITLE
How can I log all sql statements?

### ISSUE THREAD

**Issue by pitsolu** [popphp/pop-db#16]
Hi,

This is not really an issue but is there a way one can log all sql statement in `pop-db` to a log file or cli?

Would be nice to have.

**Comment by nicksagona** [comment]
Yes there is - check out the pop-debug component. It has functionality to do just that as well monitor performance (how long a query takes, etc)

**Comment by pitsolu** [comment]
```php
$debugger = new Debugger(new File('logs/sql.log'));
db()->listen(QueryHandler::class, null, new Profiler($debugger));
```
This is what I am doing but the log is empty. Where `db()` is `Pop\Db\Adapter\Pdo`

**Comment by pitsolu** [comment]
Code above works but could it use `monolog`? Could everything be logged into a single sql file `logs/sql.log` ?

**Comment by nicksagona** [comment]
Logging into a single log file can be done now. But for support for it to work with `monolog`, I believe that could be done, it would just have to be built out.

**Comment by pitsolu** [comment]
> Logging into a single log file can be done now. But for support for it to work with `monolog`, I believe that could be done, it would just have to be built out.

Example please?

**Comment by nicksagona** [comment]
So using the Profiler that comes with the `pop-db` component (that works with `pop-debug`), here's an example of how to wire up the debugger to automatically log all queries:

```php
use Pop\Debug\Debugger;
use Pop\Debug\Storage\File;
use Pop\Db\Db;
use Pop\Db\Record;
use Pop\Db\Adapter\Profiler\Profiler;

$db = Db::mysqlConnect([
    'database' => 'DATABASE',
    'username' => 'DB_USER',
    'password' => 'DB_PASS'
]);

class Users extends Record {}

Record::setDb($db);

// Register the debugger and query handler with the DB adapter
$debugger = new Debugger(new File(__DIR__ . '/log'));
$db->listen('Pop\Debug\Handler\QueryHandler', null, new Profiler($debugger));

// Save a user to the database
$user = new Users([
    'username' => 'newuser',
    'password' => 'password',
    'email'    => 'newuser@test.com'
]);

$user->save();
```

That code will produce a log file that contains:

```text
Start:			1731256645.02374
Finish:			1731256645.03594
Elapsed:		0.01220 seconds

Queries:
--------
INSERT INTO `users` (`username`, `password`, `email`) VALUES (?, ?, ?) [0.00886]
Start:			1731256645.02707
Finish:			1731256645.03593
Params:
	username => newuser
	password => password
	email => newuser@test.com

```

Your little code snippet you pasted above looks like it's in the right direction, but not sure what the rest of your code looks like after that. The example above shows the full cycle of wiring up the profiler/debug and executing a query to have it be logged. Let me know if that helps.

**Comment by nicksagona** [comment]
And regarding your question about Monolog - that's a little bit apples to oranges. Monolog, like the `pop-log` component, is a SYSLOG standard logging library. This debug component is more tightly integrating with certain system resources and concepts to produce specific logging/messaging that has to do with those systems (DB queries, memory, HTTP requests, etc.)

That said, it could prob set up our built out to integrate a SYSLOG component like Monolog or `pop-log` to fire off basic syslog messages to a logging resource when certain parameters are met (e.g., a query takes too long, etc.)

**Comment by nicksagona** [comment]
Hey - so I just pushed up a new release to pop-debug that now includes support for pop-log (v 2.1.0) With it you can either push the debug messaging to the debug storage adapter, or a syslog compliant logging resource, or both.

**Comment by pitsolu** [comment]
Thanks @nicksagona . Haven't had time to look at it, but as soon as I do I will get back to you. I understand the need to use your own logger. I am a fan of this framework. Keep the good work going (thumbs up). Please send me an email we can discuss more - currently working on an AI project, I follow you on Github.

**Comment by nicksagona** [comment]
Ok thanks - I'm going to close this issue then.
